### ISSUE TITLE
[Staging] Committed Delivery

### ISSUE THREAD

**Issue by alixcf** [Taters-Enterprises-Inc/ilovetaters#443]
Has an option to select a delivery date for the following days all week - which is opposed to the first selection of delivery date that is supposed to be every MWF (?)

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/c7d91356-f133-43f3-b633-88ea773cbf33)

_PS. di ko lang po sure kung ganun talaga kasi di ko po siya naeencounter before (yung pagselect ng date sa baba), like straight up preview order po ginagawa ko_

**Comment by knhrvs** [comment]
Ginawa ko na syang required, kaya nagkakaroon tayo ng maling  commited delivery date kasi di hindi napapopulate yung field. kaya hindi magiging open yung  preview kapag yung commited date is null and yung mga quantity is 0 or null.
