### ISSUE TITLE
[Staging] Action Icon

### ISSUE THREAD

**Issue by alixcf** [Taters-Enterprises-Inc/ilovetaters#444]
No difference on the icons on my end (for emergency)

The logistics type for the upper icon: Pick-up
The logistics type for the lower icon: Delivery

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/5c68eefd-3e9f-4acf-9081-85bc658e4d2a)

**Comment by knhrvs** [comment]
no difference talaga sila. malalaman kung delivery or pickup sa order information modal. 

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/60647311/f6af58c2-0606-4d61-ac5f-61f3276f54de)
