### ISSUE TITLE
[Staging] New Added Product won't show

### ISSUE THREAD

**Issue by alixcf** [Taters-Enterprises-Inc/ilovetaters#445]
The recently added item won't show po when I cancel the next time mag-edit po ako ng order. However, when I exit the Supplier View Modal and open ulit, nagsshow naman po complete items.

Here is the process po paano ko ginagawa:
**View order > edit > add > select item > enter quantity > confirm > modal will show up > yes > edit again > cancel** 

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/bf811394-8710-422f-93ad-18119297c55f)

**Comment by knhrvs** [comment]
### Update:

The issue has been fixed and the changes are now available for testing [staging].

If you can confirm that the issue is indeed resolved on your end, please feel free to close this issue.
