### ISSUE TITLE
[Staging] No Delivered Quantity 

### ISSUE THREAD

**Issue by alixcf** [Taters-Enterprises-Inc/ilovetaters#446]
No delivered quantity is present in the newly added products (from edit).

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/19c717b0-cfc0-48ad-b9b5-7e8526de41d2)

**Comment by alixcf** [comment]
Lumalabas lang po yung 0 (for delivered quantity) pag nagclick ng out of stock button ng dalawang beses. 
![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/efa30368-1bd2-4092-a4be-b9ba9d7f4234)

**Comment by alixcf** [comment]
Additional question po, normal po ba na accepted value pa rin yung 0 sa input field? Or dapat po if 0 ang ilalagay na value, out of stock ang icclick? 

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/04fe1916-147e-498b-af06-dfaf7c22c39e)

**Comment by alixcf** [comment]
Update: Hindi na po 0 yung nakalagay sa delivered quantity. Pero blank pa rin po when it comes to newly added products. 

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/ffaf9e13-df6d-4563-b00b-485101be6a8c)

**Comment by knhrvs** [comment]
What process to? new order?

**Comment by alixcf** [comment]
Edit order po

> What process to? new order?
