### ISSUE TITLE
[Staging] Store Receive Order

### ISSUE THREAD

**Issue by alixcf** [Taters-Enterprises-Inc/ilovetaters#447]
After po magconfirm ng order (receive order), ganito lang po lumalabas sa lower part ng screen.

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/3fc78910-d6b2-4438-b957-1a325cb3d7f5)

**Comment by alixcf** [comment]
Ganun din po lumalabas pag nageedit po ako ng order.

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/644c2f80-b6b6-4fc2-924e-05333acdb772)

**Comment by alixcf** [comment]
> After po magconfirm ng order (receive order), ganito lang po lumalabas sa lower part ng screen.
> 
> ![image](https://user-images.githubusercontent.com/144800047/278880585-3fc78910-d6b2-4438-b957-1a325cb3d7f5.png)

Nagtry po ako sa ibang order, okay naman po yung feedback. 

![image](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/c8ce4595-bf06-41bd-86d3-e82d5c681aa3)

**Comment by knhrvs** [comment]
can yo do it again then patingin ng network response

**Comment by alixcf** [comment]
Based sa naexperience ko po ngayon, after confirming order is okay na po siya. Hindi na po blank ang lumalabas sa feedback. However, yung edit po ng order, blank pa rin po. 

Eto po yung gif.

![error-edit](https://github.com/Taters-Enterprises-Inc/ilovetaters/assets/144800047/493976b9-afa3-433b-b7e0-d353aed45fce)

**Comment by knhrvs** [comment]
Fix na https://github.com/Taters-Enterprises-Inc/api/commit/72051678a6ceaa98c0de21f7867f2443469bc771
